name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      env:
        ALLOW_LATEST_GPYTORCH_LINOP: true
      run: |
        pip install git+https://github.com/cornellius-gp/linear_operator.git
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install ."[dev, tutorials]"
    - name: Validate Sphinx
      run: |
        python scripts/validate_sphinx.py -p "$(pwd)"
    - name: Run sphinx
      run: |
        # warnings treated as errors
        sphinx-build -WT --keep-going sphinx/source sphinx/build
    - name: Validate and parse tutorials
      run: |
        python scripts/convert_ipynb_to_mdx.py --clean
