name: Nightly Cron test inherit secrets

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]


jobs:
  publish-latest-website:
    name: Publish latest website
    uses: ./.github/workflows/publish_website.yml
    secrets: inherit
