name: Nightly Cron test inherit secrets

on:
  workflow_dispatch:


jobs:
  publish-latest-website:
    name: Publish latest website
    needs: [tests-and-coverage-nightly, package-test-deploy-pypi]
    uses: ./.github/workflows/publish_website.yml
    secrets: inherit
